

import java.awt.CardLayout;

import com.lowagie.text.pdf.codec.Base64.InputStream;
import com.lowagie.text.pdf.codec.Base64.OutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import static java.lang.System.in;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class MainManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainManagerGUI
     */
    public MainManagerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        upperPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        taskPanel = new javax.swing.JPanel();
        buttonShowReports = new javax.swing.JButton();
        buttonEditProfileManager = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        panelFrontPageManager = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelReports = new javax.swing.JPanel();
        panelEditProfileManager = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("ADMIN");

        javax.swing.GroupLayout upperPanel1Layout = new javax.swing.GroupLayout(upperPanel1);
        upperPanel1.setLayout(upperPanel1Layout);
        upperPanel1Layout.setHorizontalGroup(
                upperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanel1Layout.createSequentialGroup()
                                .addContainerGap(997, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81))
        );
        upperPanel1Layout.setVerticalGroup(
                upperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(upperPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addContainerGap(75, Short.MAX_VALUE))
        );

        taskPanel.setBackground(new java.awt.Color(204, 204, 204));

        buttonShowReports.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\presentation+file-1326929051950482136_24.png")); // NOI18N
        buttonShowReports.setText("Show Reports");
        buttonShowReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowReportsActionPerformed(evt);
            }
        });

        buttonEditProfileManager.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\google+optimization+repair+setting+support+icon-1320183350243067158_24.png")); // NOI18N

        buttonEditProfileManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditProfileManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout taskPanelLayout = new javax.swing.GroupLayout(taskPanel);
        taskPanel.setLayout(taskPanelLayout);
        taskPanelLayout.setHorizontalGroup(
                taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonShowReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                        .addComponent(buttonEditProfileManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        taskPanelLayout.setVerticalGroup(
                taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(buttonShowReports, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(buttonEditProfileManager, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        panelFrontPageManager.setMaximumSize(new java.awt.Dimension(2220, 2220));
        panelFrontPageManager.setPreferredSize(new java.awt.Dimension(800, 529));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Please click on 'Show Reports' to view your report");

        javax.swing.GroupLayout panelFrontPageManagerLayout = new javax.swing.GroupLayout(panelFrontPageManager);
        panelFrontPageManager.setLayout(panelFrontPageManagerLayout);
        panelFrontPageManagerLayout.setHorizontalGroup(
                panelFrontPageManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFrontPageManagerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addContainerGap(1986, Short.MAX_VALUE))
        );
        panelFrontPageManagerLayout.setVerticalGroup(
                panelFrontPageManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFrontPageManagerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addContainerGap(488, Short.MAX_VALUE))
        );

        mainPanel.add(panelFrontPageManager, "panelFrontPage");

        panelReports.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelReportsLayout = new javax.swing.GroupLayout(panelReports);
        panelReports.setLayout(panelReportsLayout);
        panelReportsLayout.setHorizontalGroup(
                panelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 2446, Short.MAX_VALUE)
        );
        panelReportsLayout.setVerticalGroup(
                panelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 521, Short.MAX_VALUE)
        );

        mainPanel.add(panelReports, "panelShowReports");

        panelEditProfileManager.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout panelEditProfileManagerLayout = new javax.swing.GroupLayout(panelEditProfileManager);
        panelEditProfileManager.setLayout(panelEditProfileManagerLayout);
        panelEditProfileManagerLayout.setHorizontalGroup(
                panelEditProfileManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 2446, Short.MAX_VALUE)
        );
        panelEditProfileManagerLayout.setVerticalGroup(
                panelEditProfileManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 521, Short.MAX_VALUE)
        );

        mainPanel.add(panelEditProfileManager, "panelEditProfileManager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(upperPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(taskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(upperPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(taskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void buttonShowReportsActionPerformed(java.awt.event.ActionEvent evt) {



        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection= DriverManager.getConnection("jdbc:mysql://localhost:3306/default", "root", "Riddhi@24");



            FileInputStream in=new FileInputStream(new File("C:\\Users\\user\\eclipse-workspace\\project\\demo.jrxml"));
            JasperDesign jd=JRXmlLoader.load(in);
            String sql;
            sql = "select * from student ";
            JRDesignQuery newQuery=new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr= JasperCompileManager.compileReport(jd);
            HashMap para=new HashMap();


            JasperPrint j=JasperFillManager.fillReport(jr, para, connection);
            JasperViewer.viewReport(j, false);

            FileOutputStream os=new FileOutputStream(new File("D:\\reports\\demo1.pdf"));
            JasperExportManager.exportReportToPdfStream(j, os);



        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();

        }
        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();
        cardLayout.show(this.mainPanel, "panelShowReports");




    }

    private void buttonEditProfileManagerActionPerformed(java.awt.event.ActionEvent evt) {

        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();
        cardLayout.show(this.mainPanel, "panelEditProfileManager");
    }


    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonEditProfileManager;
    private javax.swing.JButton buttonShowReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelEditProfileManager;
    private javax.swing.JPanel panelFrontPageManager;
    private javax.swing.JPanel panelReports;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JPanel upperPanel1;
    // End of variables declaration
}
