package LoginPage;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.CardLayout;

/**
 *
 * @author user
 */
public class MainUserGUI extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public MainUserGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taskPanel = new javax.swing.JPanel();
        buttonFillFeedback = new javax.swing.JButton();
        buttonShowPending = new javax.swing.JButton();
        buttonEditProfile = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        panelFrontPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelFillFeedback = new javax.swing.JPanel();
        panelShowPending = new javax.swing.JPanel();
        panelEditProfile = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2220, 2220));
        setPreferredSize(new java.awt.Dimension(800, 676));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("USER");

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
                upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                                .addContainerGap(997, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(81, 81, 81))
        );
        upperPanelLayout.setVerticalGroup(
                upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(upperPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(75, Short.MAX_VALUE))
        );

        taskPanel.setBackground(new java.awt.Color(204, 204, 204));

        buttonFillFeedback.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\presentation+file-1326929051950482136_24.png")); // NOI18N
        buttonFillFeedback.setText("Fill Feedback form");
        buttonFillFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFillFeedbackActionPerformed(evt);
            }
        });

        buttonShowPending.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\user-1326929053445672270_24.png")); // NOI18N
        buttonShowPending.setText("Show pending task");
        buttonShowPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowPendingActionPerformed(evt);
            }
        });

        buttonEditProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\google+optimization+repair+setting+support+icon-1320183350243067158_24.png")); // NOI18N
        buttonEditProfile.setText("Edit profile");
        buttonEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout taskPanelLayout = new javax.swing.GroupLayout(taskPanel);
        taskPanel.setLayout(taskPanelLayout);
        taskPanelLayout.setHorizontalGroup(
                taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttonFillFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonShowPending, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                        .addComponent(buttonEditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        taskPanelLayout.setVerticalGroup(
                taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(buttonFillFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(buttonShowPending, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(buttonEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        panelFrontPage.setMaximumSize(new java.awt.Dimension(2220, 2220));
        panelFrontPage.setPreferredSize(new java.awt.Dimension(800, 529));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Please click on 'Fill feedback form' to complete the Survey");

        javax.swing.GroupLayout panelFrontPageLayout = new javax.swing.GroupLayout(panelFrontPage);
        panelFrontPage.setLayout(panelFrontPageLayout);
        panelFrontPageLayout.setHorizontalGroup(
                panelFrontPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFrontPageLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addContainerGap(1914, Short.MAX_VALUE))
        );
        panelFrontPageLayout.setVerticalGroup(
                panelFrontPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFrontPageLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addContainerGap(496, Short.MAX_VALUE))
        );

        mainPanel.add(panelFrontPage, "panelFrontPage");

        panelFillFeedback.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelFillFeedbackLayout = new javax.swing.GroupLayout(panelFillFeedback);
        panelFillFeedback.setLayout(panelFillFeedbackLayout);
        panelFillFeedbackLayout.setHorizontalGroup(
                panelFillFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 2446, Short.MAX_VALUE)
        );
        panelFillFeedbackLayout.setVerticalGroup(
                panelFillFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 529, Short.MAX_VALUE)
        );

        mainPanel.add(panelFillFeedback, "panelFillFeedback");

        panelShowPending.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelShowPendingLayout = new javax.swing.GroupLayout(panelShowPending);
        panelShowPending.setLayout(panelShowPendingLayout);
        panelShowPendingLayout.setHorizontalGroup(
                panelShowPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 2446, Short.MAX_VALUE)
        );
        panelShowPendingLayout.setVerticalGroup(
                panelShowPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 529, Short.MAX_VALUE)
        );

        mainPanel.add(panelShowPending, "panelShowPending");

        panelEditProfile.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout panelEditProfileLayout = new javax.swing.GroupLayout(panelEditProfile);
        panelEditProfile.setLayout(panelEditProfileLayout);
        panelEditProfileLayout.setHorizontalGroup(
                panelEditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 2446, Short.MAX_VALUE)
        );
        panelEditProfileLayout.setVerticalGroup(
                panelEditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 529, Short.MAX_VALUE)
        );

        mainPanel.add(panelEditProfile, "panelEditProfile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(upperPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(taskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(taskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void buttonFillFeedbackActionPerformed(java.awt.event.ActionEvent evt) {

        /*  mainPanel.removeAll();
        mainPanel.add(fillFeedback1);
        mainPanel.revalidate();
        */
        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();
        cardLayout.show(this.mainPanel, "panelFillFeedback");
        // TODO add your handling code here:
    }

    private void buttonShowPendingActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        /*mainPanel.removeAll();
        mainPanel.add(pendingTask1);
        mainPanel.revalidate();

        */
        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();
        cardLayout.show(this.mainPanel, "panelShowPending");


    }

    private void buttonEditProfileActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) this.mainPanel.getLayout();
        cardLayout.show(this.mainPanel, "panelEditProfile");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new MainUserGUI().setVisible(true);
                    }
                });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonEditProfile;
    private javax.swing.JButton buttonFillFeedback;
    private javax.swing.JButton buttonShowPending;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelEditProfile;
    private javax.swing.JPanel panelFillFeedback;
    private javax.swing.JPanel panelFrontPage;
    private javax.swing.JPanel panelShowPending;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration
}